export const SCANNER_STATES = {
  IDLE: "IDLE",
  INITIALIZING_CAMERA: "INITIALIZING_CAMERA",
  SEARCHING: "SEARCHING",
  DOCUMENT_DETECTED: "DOCUMENT_DETECTED",
  ALIGNING: "ALIGNING",
  STABILIZING: "STABILIZING",
  CAPTURING: "CAPTURING",
  PROCESSING: "PROCESSING",
  VERIFYING: "VERIFYING",
  RESULT: "RESULT",
  ERROR: "ERROR",
};
