export const ACTIONS = {
  NAVIGATE_STEP: "NAVIGATE_STEP",
  NEXT: "NEXT",
  PREVIOUS: "PREVIOUS",
  FILL_FIELD: "FILL_FIELD",
  CLEAR_FIELD: "CLEAR_FIELD",
  SELECT_OPTION: "SELECT_OPTION",
  READ_FIELD: "READ_FIELD",
  EXPLAIN_FIELD: "EXPLAIN_FIELD",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  OPEN_SCANNER: "OPEN_SCANNER",
  OPEN_FILE_PICKER: "OPEN_FILE_PICKER",
  SUBMIT: "SUBMIT",
  NAVIGATE_PAGE: "NAVIGATE_PAGE",
  RESTART_FORM: "RESTART_FORM"
};
